---
# Image will be published to your GitHub container registry
name: bazzite-testbed
description: Custom Bazzite image with KDE, dev tools, and remote access.

# We are using the standard KDE Plasma Bazzite AMD/Intel image
base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: rpm-ostree
    install:
      # Core system tools and terminal shells
      - zsh
      - fish

  - type: default-flatpaks@v1
    notify: true
    system:
      install:
        # Development & 3D
        - org.godotengine.Godot
        - com.chitubox.CHITUBOX
        
        # Web Access & Work Remote Desktop Webclient
        - com.google.Chrome
        - com.microsoft.Edge
        - org.mozilla.Thunderbird
        
        # Remote Support
        - com.rustdesk.RustDesk
        
        # Media
        - com.spotify.Client

  - type: systemd
    system:
      enabled:
        # Enables Secure Shell for command-line remote access
        - sshd
        

