name: Chunked ISO Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - uses: actions/checkout@v5
      - name: Build ISO
        run: |
          curl -fsSL https://raw.githubusercontent.com/blue-build/cli/main/install.sh | bash
          DATE=$(date +%Y%m%d)
          bluebuild generate-iso --iso-name LemonKaijuOS-${DATE}.iso --output-dir ./output recipe recipes/recipe.yml
      - name: List Files
        run: |
          echo "Files in output:"
          ls -la ./output/ || echo "No output directory" 